### ISSUE TITLE
SSL/TLS编程实践

### ISSUE THREAD

**Issue by xhcoding** [xhcoding/blog-comment#8]
https://xhcoding.cn/post/20210805164933-ssl_tls编程实践/

**Comment by jkup64** [comment]
# “自签名”报错
当我完成上述单向认证中操作后，运行client给出了报错`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1129)`
但是当我将client中`context.load_verify_locations("ca.crt")`改为`context.load_verify_locations("server.crt")`程序能正常运行，我不明白为什么会这样？

我认为client需要指定ca的公钥，指定ca公钥才能对ca颁布给server的证书进行验签。但是上面的操作显示我的理解似乎有问题，您能解答我的疑惑吗？

**Comment by xhcoding** [comment]
> @oh-jka
> # “自签名”报错
> 当我完成上述单向认证中操作后，运行client给出了报错`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1129)`
> 但是当我将client中`context.load_verify_locations("ca.crt")`改为`context.load_verify_locations("server.crt")`程序能正常运行，我不明白为什么会这样？
> 
> 我认为client需要指定ca的公钥，指定ca公钥才能对ca颁布给server的证书进行验签。但是上面的操作显示我的理解似乎有问题，您能解答我的疑惑吗？

我这边是没有这个问题的，client 就是需要 ca 的公钥，所以才需要用 ca.crt 。不确定是不是你的证书生成有问题
